<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.2.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="8.0.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="VideoOS.Platform.SDK">
      <HintPath>..\milestonesystems.videoos.platform.sdk.25.3.2\lib\net472\VideoOS.Platform.SDK.dll</HintPath>
    </Reference>
    <Reference Include="VideoOS.Platform.SDK.Export">
      <HintPath>..\milestonesystems.videoos.platform.sdk.25.3.2\lib\net472\VideoOS.Platform.SDK.Export.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
